---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 2
  require_ruby_for_busser: false
  require_chef_for_busser: true
  hosts: all

platforms:
  - name: ubuntu-16.04
    driver_config:
      box: bento/ubuntu-16.04

suites:
  - name: default