---
- htpasswd:
    path: "{{ nginx_htpasswd_file_path }}"
    name: "{{ item.user_name }}"
    password: "{{ item.password }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0640
  with_items: "{{ nginx_basic_auth_users }}"
  when: nginx_basic_auth_required